### ISSUE TITLE
触控延迟和悬浮窗拦截问题

### ISSUE THREAD

**Issue by explorer-exe-bilibili** [Alan-CRL/Inkeys#34]
和希沃展台同时打开时会有接近半秒的触控延迟。
最新版的希沃白班，悬浮窗不能成功拦截，增强模式也不行。
环境：
win7，6代i5（具体的不记得了），核显，希沃一体机

**Comment by Alan-CRL** [comment]
收到了，我马上开始排查

**Comment by Alan-CRL** [comment]
@explorer-exe-bilibili 经过我在 win11 上的测试，发现两个问题均没有复现。你需要提供智绘教的版本，和更详细的信息。不过需要注意的是 win7 不是使用智绘教的最佳选择，我建议你升级到 win10。win7 上的问题有可能无法修复或者不被重视，但我也会尝试为你解决。

**Comment by explorer-exe-bilibili** [comment]
> @explorer-exe-bilibili 经过我在 win11 上的测试，发现两个问题均没有复现。你需要提供智绘教的版本，和更详细的信息。不过需要注意的是 win7 不是使用智绘教的最佳选择，我建议你升级到 win10。win7 上的问题有可能无法修复或者不被重视，但我也会尝试为你解决。

好的..我也稍微会一些cpp，可以试试一起帮你们排查🥳

**Comment by explorer-exe-bilibili** [comment]
智绘教的版本是最新的正式版24h2

**Comment by explorer-exe-bilibili** [comment]
另外...抱歉这么久才回，刚下晚自习没多久😢

**Comment by YiTTT-FlY** [comment]
> @explorer-exe-bilibili 经过我在 win11 上的测试，发现两个问题均没有复现。你需要提供智绘教的版本，和更详细的信息。不过需要注意的是 win7 不是使用智绘教的最佳选择，我建议你升级到 win10。win7 上的问题有可能无法修复或者不被重视，但我也会尝试为你解决。

添加个反馈：七代i3（7100）的希沃（win10 1909x64 和win10 22H2x64都试过）和八代低压笔记本u（win10 22H2）占用cpu率过高，24~30%这样子，使用卡顿且打开希沃白板就会卡顿，没在希沃上截图。卓越性能解开使用了
在本人的i3-12100F上占用率在3~4%，使用流畅。
不清楚是哪里出了问题。。。。。。

**Comment by YiTTT-FlY** [comment]
> 收到了，我马上开始排查

添加个反馈：七代i3（7100）的希沃（win10 1909x64 和win10 22H2x64都试过）和八代低压笔记本u（win10 22H2）占用cpu率过高，2430%这样子，使用卡顿且打开希沃白板就会卡顿，没在希沃上截图。卓越性能解开使用了
在本人的i3-12100F上占用率在34%，使用流畅。
不清楚是哪里出了问题。。。。。。

**Comment by Alan-CRL** [comment]
是不是使用了高于 1080P 的分辨率？

**Comment by Alan-CRL** [comment]
抱歉，你需要提供详细的程序版本，位于 选项->软件版本下的 程序发布版本。后续联系估计需要您加下我的QQ 2685549821。
![智绘教_MX77PeaiiC](https://github.com/user-attachments/assets/167fe1a7-9af0-4be9-b650-fc082c7ca00e)
![智绘教_8UyhZtvBkJ](https://github.com/user-attachments/assets/8e12e76d-b06c-49be-a921-5957acff3c5b)

**Comment by explorer-exe-bilibili** [comment]
好的，版本我下午去看看，分辨率就是正好1080p

**Comment by explorer-exe-bilibili** [comment]
> > 收到了，我马上开始排查
> 
> 添加个反馈：七代i3（7100）的希沃（win10 1909x64 和win10 22H2x64都试过）和八代低压笔记本u（win10 22H2）占用cpu率过高，2430%这样子，使用卡顿且打开希沃白板就会卡顿，没在希沃上截图。卓越性能解开使用了
> 在本人的i3-12100F上占用率在34%，使用流畅。
> 不清楚是哪里出了问题。。。。。。

希沃的CPU带不动，软件优化有点差了😓

**Comment by YiTTT-FlY** [comment]
> 是不是使用了高于 1080P 的分辨率？

使用的分辨率是1920×1080，60.000hz刷新率

**Comment by Alan-CRL** [comment]
只能等待后续优化吧

**Comment by Alan-CRL** [comment]
该问题无法复现或并不存在
