### ISSUE TITLE
无法锁定正确的wpp进程

### ISSUE THREAD

**Issue by huangyxHUTAO** [Alan-CRL/Inkeys#35]
wps貌似会让一个多余的wpp进程运行，导致无法锁定正确的wpp进程

这是关于这个bug的视频
https://github.com/user-attachments/assets/c676c51b-469f-4b35-9c71-9214927564f2

我用bat写了一个小脚本来结束旧的wpp.exe进程

https://github.com/user-attachments/assets/e076b3c5-0044-4693-a79c-08fb6d0731ae

```bat
@echo off
:loop
tasklist /FI "IMAGENAME eq wps.exe" | find /I /N "wps.exe" >NUL
if "%ERRORLEVEL%"=="1" (
    echo wps.exe进程不存在，正在结束wpp.exe进程...
    taskkill /IM wpp.exe /F >NUL 2>&1
    echo wpp.exe进程已结束，等待wps.exe进程启动...
    goto wait
) else (
    echo wps.exe进程正在运行，继续监控...
    timeout /t 1 >NUL
    goto loop
)

:wait
tasklist /FI "IMAGENAME eq wps.exe" | find /I /N "wps.exe" >NUL
if "%ERRORLEVEL%"=="0" (
    echo wps.exe进程已启动，继续监控...
    goto loop
) else (
    timeout /t 1 >NUL
    goto wait
)
```
但是这个代码偶尔也无法正常运行，因为关闭wps时wps.exe不一定会结束，但是概率很小，不知道为什么

**Comment by Alan-CRL** [comment]
好的我已经收到了这个 BUG 反馈，稍后研究一下

**Comment by Alan-CRL** [comment]
@huangyxHUTAO 似乎这个多余的 wpp 进程从第一个放映窗口打开后就一直存在，即使第二个放映窗口打开后也不会自动关闭？

**Comment by Alan-CRL** [comment]
@huangyxHUTAO 为何关闭此 issues？

**Comment by huangyxHUTAO** [comment]
点错了(误

**Comment by huangyxHUTAO** [comment]
是的，我在学校内测试过
学校电脑从上午第一节课老师关闭wps后， 智绘教 就再也没有锁定过进程

实际上有自动关闭，但是wps进程在运行时貌似之前的wpp进程就不会结束
如果wps关闭后，大约5~20分钟，才(可能)会结束wpp

**Comment by Alan-CRL** [comment]
这似乎是存在很久的 BUG，但是这次 WPS 新版本似乎加重了。以前的版本也会出现游离的多余 wpp.exe，但是这应该不会影响智绘教把？我尝试复习时，出现 2 个 wps.exe。而智绘教是锁定 wps.exe 的，故有这个问题

**Comment by Alan-CRL** [comment]
@huangyxHUTAO 我需要进一步进行交流。请加下我的QQ2685549821

**Comment by Alan-CRL** [comment]
该问题已经修复，但是不保证其行为符合预期，需要您至下一个版本发布时自行验证。
