### ISSUE TITLE
logo 优化

### ISSUE THREAD

**Issue by dream-pep** [Alan-CRL/Inkeys#40]
希望可以找一个人做一下 logo 与内容优化
（实在没办法的话也可以找我:qq109554382，记得打备注）

**Comment by Alan-CRL** [comment]
Inkeys2 已经启用了新的软件 Logo，并会在下一个版本中启用，目前不考虑重新制作。

![Inkeys2 - 1024x](https://github.com/user-attachments/assets/a6779c0d-aaeb-4b70-96f8-a4d4bdb874d2)
